/**
 * Integration
 *          Here can be some description if that needed     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.Date;
import org.openapitools.client.model.OrderDtoDeliveryAddress;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class OrderDto {
  
  @SerializedName("id")
  private String id = null;
  public enum OrderStatusEnum {
     CLOSED,  OPENED, 
  };
  @SerializedName("orderStatus")
  private OrderStatusEnum orderStatus = null;
  @SerializedName("customerId")
  private String customerId = null;
  @SerializedName("deliveryAddress")
  private OrderDtoDeliveryAddress deliveryAddress = null;
  public enum LastSyncStatusEnum {
     ERROR,  SUCCESS,  UNKNOWN, 
  };
  @SerializedName("lastSyncStatus")
  private LastSyncStatusEnum lastSyncStatus = null;
  @SerializedName("deliveredVolume")
  private BigDecimal deliveredVolume = null;
  @SerializedName("createdAt")
  private Date createdAt = null;
  @SerializedName("updatedAt")
  private Date updatedAt = null;
  @SerializedName("lastSyncAt")
  private Date lastSyncAt = null;
  @SerializedName("documentNumber")
  private String documentNumber = null;
  @SerializedName("projectNumber")
  private String projectNumber = null;
  @SerializedName("salesResponsible")
  private String salesResponsible = null;
  @SerializedName("orderDate")
  private String orderDate = null;
  @SerializedName("deliveryDate")
  private String deliveryDate = null;
  @SerializedName("plannedStartDate")
  private String plannedStartDate = null;
  @SerializedName("deletedAt")
  private Date deletedAt = null;
  @SerializedName("updatedBy")
  private String updatedBy = null;
  @SerializedName("deliveryName")
  private String deliveryName = null;
  @SerializedName("deliveryLineCount")
  private BigDecimal deliveryLineCount = null;

  /**
   * Ordernummer
   **/
  @ApiModelProperty(required = true, value = "Ordernummer")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Orderstatus
   **/
  @ApiModelProperty(required = true, value = "Orderstatus")
  public OrderStatusEnum getOrderStatus() {
    return orderStatus;
  }
  public void setOrderStatus(OrderStatusEnum orderStatus) {
    this.orderStatus = orderStatus;
  }

  /**
   * Kund
   **/
  @ApiModelProperty(required = true, value = "Kund")
  public String getCustomerId() {
    return customerId;
  }
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public OrderDtoDeliveryAddress getDeliveryAddress() {
    return deliveryAddress;
  }
  public void setDeliveryAddress(OrderDtoDeliveryAddress deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  /**
   * Synkronisering status
   **/
  @ApiModelProperty(required = true, value = "Synkronisering status")
  public LastSyncStatusEnum getLastSyncStatus() {
    return lastSyncStatus;
  }
  public void setLastSyncStatus(LastSyncStatusEnum lastSyncStatus) {
    this.lastSyncStatus = lastSyncStatus;
  }

  /**
   * Levererad volym
   **/
  @ApiModelProperty(required = true, value = "Levererad volym")
  public BigDecimal getDeliveredVolume() {
    return deliveredVolume;
  }
  public void setDeliveredVolume(BigDecimal deliveredVolume) {
    this.deliveredVolume = deliveredVolume;
  }

  /**
   * Skapades
   **/
  @ApiModelProperty(required = true, value = "Skapades")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * Senast ändrad
   **/
  @ApiModelProperty(required = true, value = "Senast ändrad")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * Synkronisera
   **/
  @ApiModelProperty(required = true, value = "Synkronisera")
  public Date getLastSyncAt() {
    return lastSyncAt;
  }
  public void setLastSyncAt(Date lastSyncAt) {
    this.lastSyncAt = lastSyncAt;
  }

  /**
   * Dokumentnummer
   **/
  @ApiModelProperty(value = "Dokumentnummer")
  public String getDocumentNumber() {
    return documentNumber;
  }
  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }

  /**
   * Projektnummer
   **/
  @ApiModelProperty(value = "Projektnummer")
  public String getProjectNumber() {
    return projectNumber;
  }
  public void setProjectNumber(String projectNumber) {
    this.projectNumber = projectNumber;
  }

  /**
   * Ansvarig säljare
   **/
  @ApiModelProperty(value = "Ansvarig säljare")
  public String getSalesResponsible() {
    return salesResponsible;
  }
  public void setSalesResponsible(String salesResponsible) {
    this.salesResponsible = salesResponsible;
  }

  /**
   * Orderdatum
   **/
  @ApiModelProperty(value = "Orderdatum")
  public String getOrderDate() {
    return orderDate;
  }
  public void setOrderDate(String orderDate) {
    this.orderDate = orderDate;
  }

  /**
   * Leveransdatum
   **/
  @ApiModelProperty(value = "Leveransdatum")
  public String getDeliveryDate() {
    return deliveryDate;
  }
  public void setDeliveryDate(String deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  /**
   * Planerat Startdatum
   **/
  @ApiModelProperty(value = "Planerat Startdatum")
  public String getPlannedStartDate() {
    return plannedStartDate;
  }
  public void setPlannedStartDate(String plannedStartDate) {
    this.plannedStartDate = plannedStartDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDeletedAt() {
    return deletedAt;
  }
  public void setDeletedAt(Date deletedAt) {
    this.deletedAt = deletedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUpdatedBy() {
    return updatedBy;
  }
  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  /**
   * Mottagarnamn
   **/
  @ApiModelProperty(value = "Mottagarnamn")
  public String getDeliveryName() {
    return deliveryName;
  }
  public void setDeliveryName(String deliveryName) {
    this.deliveryName = deliveryName;
  }

  /**
   * Leveranser
   **/
  @ApiModelProperty(value = "Leveranser")
  public BigDecimal getDeliveryLineCount() {
    return deliveryLineCount;
  }
  public void setDeliveryLineCount(BigDecimal deliveryLineCount) {
    this.deliveryLineCount = deliveryLineCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDto orderDto = (OrderDto) o;
    return (this.id == null ? orderDto.id == null : this.id.equals(orderDto.id)) &&
        (this.orderStatus == null ? orderDto.orderStatus == null : this.orderStatus.equals(orderDto.orderStatus)) &&
        (this.customerId == null ? orderDto.customerId == null : this.customerId.equals(orderDto.customerId)) &&
        (this.deliveryAddress == null ? orderDto.deliveryAddress == null : this.deliveryAddress.equals(orderDto.deliveryAddress)) &&
        (this.lastSyncStatus == null ? orderDto.lastSyncStatus == null : this.lastSyncStatus.equals(orderDto.lastSyncStatus)) &&
        (this.deliveredVolume == null ? orderDto.deliveredVolume == null : this.deliveredVolume.equals(orderDto.deliveredVolume)) &&
        (this.createdAt == null ? orderDto.createdAt == null : this.createdAt.equals(orderDto.createdAt)) &&
        (this.updatedAt == null ? orderDto.updatedAt == null : this.updatedAt.equals(orderDto.updatedAt)) &&
        (this.lastSyncAt == null ? orderDto.lastSyncAt == null : this.lastSyncAt.equals(orderDto.lastSyncAt)) &&
        (this.documentNumber == null ? orderDto.documentNumber == null : this.documentNumber.equals(orderDto.documentNumber)) &&
        (this.projectNumber == null ? orderDto.projectNumber == null : this.projectNumber.equals(orderDto.projectNumber)) &&
        (this.salesResponsible == null ? orderDto.salesResponsible == null : this.salesResponsible.equals(orderDto.salesResponsible)) &&
        (this.orderDate == null ? orderDto.orderDate == null : this.orderDate.equals(orderDto.orderDate)) &&
        (this.deliveryDate == null ? orderDto.deliveryDate == null : this.deliveryDate.equals(orderDto.deliveryDate)) &&
        (this.plannedStartDate == null ? orderDto.plannedStartDate == null : this.plannedStartDate.equals(orderDto.plannedStartDate)) &&
        (this.deletedAt == null ? orderDto.deletedAt == null : this.deletedAt.equals(orderDto.deletedAt)) &&
        (this.updatedBy == null ? orderDto.updatedBy == null : this.updatedBy.equals(orderDto.updatedBy)) &&
        (this.deliveryName == null ? orderDto.deliveryName == null : this.deliveryName.equals(orderDto.deliveryName)) &&
        (this.deliveryLineCount == null ? orderDto.deliveryLineCount == null : this.deliveryLineCount.equals(orderDto.deliveryLineCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.orderStatus == null ? 0: this.orderStatus.hashCode());
    result = 31 * result + (this.customerId == null ? 0: this.customerId.hashCode());
    result = 31 * result + (this.deliveryAddress == null ? 0: this.deliveryAddress.hashCode());
    result = 31 * result + (this.lastSyncStatus == null ? 0: this.lastSyncStatus.hashCode());
    result = 31 * result + (this.deliveredVolume == null ? 0: this.deliveredVolume.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.lastSyncAt == null ? 0: this.lastSyncAt.hashCode());
    result = 31 * result + (this.documentNumber == null ? 0: this.documentNumber.hashCode());
    result = 31 * result + (this.projectNumber == null ? 0: this.projectNumber.hashCode());
    result = 31 * result + (this.salesResponsible == null ? 0: this.salesResponsible.hashCode());
    result = 31 * result + (this.orderDate == null ? 0: this.orderDate.hashCode());
    result = 31 * result + (this.deliveryDate == null ? 0: this.deliveryDate.hashCode());
    result = 31 * result + (this.plannedStartDate == null ? 0: this.plannedStartDate.hashCode());
    result = 31 * result + (this.deletedAt == null ? 0: this.deletedAt.hashCode());
    result = 31 * result + (this.updatedBy == null ? 0: this.updatedBy.hashCode());
    result = 31 * result + (this.deliveryName == null ? 0: this.deliveryName.hashCode());
    result = 31 * result + (this.deliveryLineCount == null ? 0: this.deliveryLineCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDto {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  orderStatus: ").append(orderStatus).append("\n");
    sb.append("  customerId: ").append(customerId).append("\n");
    sb.append("  deliveryAddress: ").append(deliveryAddress).append("\n");
    sb.append("  lastSyncStatus: ").append(lastSyncStatus).append("\n");
    sb.append("  deliveredVolume: ").append(deliveredVolume).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  lastSyncAt: ").append(lastSyncAt).append("\n");
    sb.append("  documentNumber: ").append(documentNumber).append("\n");
    sb.append("  projectNumber: ").append(projectNumber).append("\n");
    sb.append("  salesResponsible: ").append(salesResponsible).append("\n");
    sb.append("  orderDate: ").append(orderDate).append("\n");
    sb.append("  deliveryDate: ").append(deliveryDate).append("\n");
    sb.append("  plannedStartDate: ").append(plannedStartDate).append("\n");
    sb.append("  deletedAt: ").append(deletedAt).append("\n");
    sb.append("  updatedBy: ").append(updatedBy).append("\n");
    sb.append("  deliveryName: ").append(deliveryName).append("\n");
    sb.append("  deliveryLineCount: ").append(deliveryLineCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
