# coding: utf-8

"""
    Integration

             Here can be some description if that needed       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.validation_error_dto import ValidationErrorDto
from openapi_client import configuration


class TestValidationErrorDto(unittest.TestCase):
    """ValidationErrorDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
