# coding: utf-8

"""
    Integration

             Here can be some description if that needed       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.delivery_address_dto import DeliveryAddressDto
from openapi_client import configuration


class TestDeliveryAddressDto(unittest.TestCase):
    """DeliveryAddressDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
