=begin
#Integration

#         Here can be some description if that needed     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/delivery_address_dto'
require 'openapi_client/models/error_dto'
require 'openapi_client/models/error_meta_dto'
require 'openapi_client/models/order_dto'
require 'openapi_client/models/order_dto_delivery_address'
require 'openapi_client/models/read_order400_response'
require 'openapi_client/models/server_error_dto'
require 'openapi_client/models/unauthorized_error_dto'
require 'openapi_client/models/validation_error_dto'

# APIs
require 'openapi_client/api/orders_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
