# coding: utf-8

"""
    Integration

             Here can be some description if that needed       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_ext_v1_0_orders.get import ListOrders
from openapi_client.paths.api_ext_v1_0_orders_order_number.get import ReadOrder


class OrdersApi(
    ListOrders,
    ReadOrder,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
