/*
 * Integration
 *
 *          Here can be some description if that needed     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDto
        //private OrderDto instance;

        public OrderDtoTests()
        {
            // TODO uncomment below to create an instance of OrderDto
            //instance = new OrderDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDto
        /// </summary>
        [Fact]
        public void OrderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDto
            //Assert.IsType<OrderDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OrderStatus'
        /// </summary>
        [Fact]
        public void OrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatus'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'DeliveryAddress'
        /// </summary>
        [Fact]
        public void DeliveryAddressTest()
        {
            // TODO unit test for the property 'DeliveryAddress'
        }
        /// <summary>
        /// Test the property 'LastSyncStatus'
        /// </summary>
        [Fact]
        public void LastSyncStatusTest()
        {
            // TODO unit test for the property 'LastSyncStatus'
        }
        /// <summary>
        /// Test the property 'DeliveredVolume'
        /// </summary>
        [Fact]
        public void DeliveredVolumeTest()
        {
            // TODO unit test for the property 'DeliveredVolume'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'LastSyncAt'
        /// </summary>
        [Fact]
        public void LastSyncAtTest()
        {
            // TODO unit test for the property 'LastSyncAt'
        }
        /// <summary>
        /// Test the property 'DocumentNumber'
        /// </summary>
        [Fact]
        public void DocumentNumberTest()
        {
            // TODO unit test for the property 'DocumentNumber'
        }
        /// <summary>
        /// Test the property 'ProjectNumber'
        /// </summary>
        [Fact]
        public void ProjectNumberTest()
        {
            // TODO unit test for the property 'ProjectNumber'
        }
        /// <summary>
        /// Test the property 'SalesResponsible'
        /// </summary>
        [Fact]
        public void SalesResponsibleTest()
        {
            // TODO unit test for the property 'SalesResponsible'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Fact]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'DeliveryDate'
        /// </summary>
        [Fact]
        public void DeliveryDateTest()
        {
            // TODO unit test for the property 'DeliveryDate'
        }
        /// <summary>
        /// Test the property 'PlannedStartDate'
        /// </summary>
        [Fact]
        public void PlannedStartDateTest()
        {
            // TODO unit test for the property 'PlannedStartDate'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Fact]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'DeliveryName'
        /// </summary>
        [Fact]
        public void DeliveryNameTest()
        {
            // TODO unit test for the property 'DeliveryName'
        }
        /// <summary>
        /// Test the property 'DeliveryLineCount'
        /// </summary>
        [Fact]
        public void DeliveryLineCountTest()
        {
            // TODO unit test for the property 'DeliveryLineCount'
        }

    }

}
