=begin
#Integration

#         Here can be some description if that needed     

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1-SNAPSHOT

=end

module OpenapiClient
  VERSION = '1.0.0'
end
