/*
 * Integration
 *
 *          Here can be some description if that needed     
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ReadOrder400Response
    /// </summary>
    [JsonConverter(typeof(ReadOrder400ResponseJsonConverter))]
    [DataContract(Name = "readOrder_400_response")]
    public partial class ReadOrder400Response : AbstractOpenAPISchema, IEquatable<ReadOrder400Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReadOrder400Response" /> class
        /// with the <see cref="ErrorDto" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ErrorDto.</param>
        public ReadOrder400Response(ErrorDto actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReadOrder400Response" /> class
        /// with the <see cref="ValidationErrorDto" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValidationErrorDto.</param>
        public ReadOrder400Response(ValidationErrorDto actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ErrorDto))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValidationErrorDto))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ErrorDto, ValidationErrorDto");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ErrorDto`. If the actual instance is not `ErrorDto`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ErrorDto</returns>
        public ErrorDto GetErrorDto()
        {
            return (ErrorDto)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ValidationErrorDto`. If the actual instance is not `ValidationErrorDto`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValidationErrorDto</returns>
        public ValidationErrorDto GetValidationErrorDto()
        {
            return (ValidationErrorDto)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReadOrder400Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ReadOrder400Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ReadOrder400Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ReadOrder400Response</returns>
        public static ReadOrder400Response FromJson(string jsonString)
        {
            ReadOrder400Response newReadOrder400Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newReadOrder400Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ErrorDto).GetProperty("AdditionalProperties") == null)
                {
                    newReadOrder400Response = new ReadOrder400Response(JsonConvert.DeserializeObject<ErrorDto>(jsonString, ReadOrder400Response.SerializerSettings));
                }
                else
                {
                    newReadOrder400Response = new ReadOrder400Response(JsonConvert.DeserializeObject<ErrorDto>(jsonString, ReadOrder400Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ErrorDto");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ErrorDto: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ValidationErrorDto).GetProperty("AdditionalProperties") == null)
                {
                    newReadOrder400Response = new ReadOrder400Response(JsonConvert.DeserializeObject<ValidationErrorDto>(jsonString, ReadOrder400Response.SerializerSettings));
                }
                else
                {
                    newReadOrder400Response = new ReadOrder400Response(JsonConvert.DeserializeObject<ValidationErrorDto>(jsonString, ReadOrder400Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ValidationErrorDto");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValidationErrorDto: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newReadOrder400Response;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReadOrder400Response);
        }

        /// <summary>
        /// Returns true if ReadOrder400Response instances are equal
        /// </summary>
        /// <param name="input">Instance of ReadOrder400Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReadOrder400Response input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ReadOrder400Response
    /// </summary>
    public class ReadOrder400ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ReadOrder400Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ReadOrder400Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
