/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key 
 * @param `value` 
 * @param msg 
 */

data class ErrorMetaDto (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.Any,

    @Json(name = "msg")
    val msg: kotlin.String

)

