/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OrderDtoDeliveryAddress

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id Ordernummer
 * @param orderStatus Orderstatus
 * @param customerId Kund
 * @param deliveryAddress 
 * @param lastSyncStatus Synkronisering status
 * @param deliveredVolume Levererad volym
 * @param createdAt Skapades
 * @param updatedAt Senast ändrad
 * @param lastSyncAt Synkronisera
 * @param documentNumber Dokumentnummer
 * @param projectNumber Projektnummer
 * @param salesResponsible Ansvarig säljare
 * @param orderDate Orderdatum
 * @param deliveryDate Leveransdatum
 * @param plannedStartDate Planerat Startdatum
 * @param deletedAt 
 * @param updatedBy 
 * @param deliveryName Mottagarnamn
 * @param deliveryLineCount Leveranser
 */

data class OrderDto (

    /* Ordernummer */
    @Json(name = "id")
    val id: kotlin.String,

    /* Orderstatus */
    @Json(name = "orderStatus")
    val orderStatus: OrderDto.OrderStatus,

    /* Kund */
    @Json(name = "customerId")
    val customerId: kotlin.String,

    @Json(name = "deliveryAddress")
    val deliveryAddress: OrderDtoDeliveryAddress,

    /* Synkronisering status */
    @Json(name = "lastSyncStatus")
    val lastSyncStatus: OrderDto.LastSyncStatus,

    /* Levererad volym */
    @Json(name = "deliveredVolume")
    val deliveredVolume: java.math.BigDecimal,

    /* Skapades */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Senast ändrad */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Synkronisera */
    @Json(name = "lastSyncAt")
    val lastSyncAt: java.time.OffsetDateTime?,

    /* Dokumentnummer */
    @Json(name = "documentNumber")
    val documentNumber: kotlin.String? = null,

    /* Projektnummer */
    @Json(name = "projectNumber")
    val projectNumber: kotlin.String? = null,

    /* Ansvarig säljare */
    @Json(name = "salesResponsible")
    val salesResponsible: kotlin.String? = null,

    /* Orderdatum */
    @Json(name = "orderDate")
    val orderDate: kotlin.String? = null,

    /* Leveransdatum */
    @Json(name = "deliveryDate")
    val deliveryDate: kotlin.String? = null,

    /* Planerat Startdatum */
    @Json(name = "plannedStartDate")
    val plannedStartDate: kotlin.String? = null,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedBy")
    val updatedBy: kotlin.String? = null,

    /* Mottagarnamn */
    @Json(name = "deliveryName")
    val deliveryName: kotlin.String? = null,

    /* Leveranser */
    @Json(name = "deliveryLineCount")
    val deliveryLineCount: java.math.BigDecimal? = null

) {

    /**
     * Orderstatus
     *
     * Values: cLOSED,oPENED
     */
    enum class OrderStatus(val value: kotlin.String) {
        @Json(name = "CLOSED") cLOSED("CLOSED"),
        @Json(name = "OPENED") oPENED("OPENED");
    }
    /**
     * Synkronisering status
     *
     * Values: eRROR,sUCCESS,uNKNOWN
     */
    enum class LastSyncStatus(val value: kotlin.String) {
        @Json(name = "ERROR") eRROR("ERROR"),
        @Json(name = "SUCCESS") sUCCESS("SUCCESS"),
        @Json(name = "UNKNOWN") uNKNOWN("UNKNOWN");
    }
}

