/**
 * Integration
 *          Here can be some description if that needed     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import org.openapitools.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("DeliveryAddressDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<DeliveryAddressDto>>(){}.getType();
    }
    
    if ("ErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<ErrorDto>>(){}.getType();
    }
    
    if ("ErrorMetaDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<ErrorMetaDto>>(){}.getType();
    }
    
    if ("OrderDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<OrderDto>>(){}.getType();
    }
    
    if ("OrderDtoDeliveryAddress".equalsIgnoreCase(className)) {
      return new TypeToken<List<OrderDtoDeliveryAddress>>(){}.getType();
    }
    
    if ("ReadOrder400Response".equalsIgnoreCase(className)) {
      return new TypeToken<List<ReadOrder400Response>>(){}.getType();
    }
    
    if ("ServerErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<ServerErrorDto>>(){}.getType();
    }
    
    if ("UnauthorizedErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<UnauthorizedErrorDto>>(){}.getType();
    }
    
    if ("ValidationErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<List<ValidationErrorDto>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("DeliveryAddressDto".equalsIgnoreCase(className)) {
      return new TypeToken<DeliveryAddressDto>(){}.getType();
    }
    
    if ("ErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<ErrorDto>(){}.getType();
    }
    
    if ("ErrorMetaDto".equalsIgnoreCase(className)) {
      return new TypeToken<ErrorMetaDto>(){}.getType();
    }
    
    if ("OrderDto".equalsIgnoreCase(className)) {
      return new TypeToken<OrderDto>(){}.getType();
    }
    
    if ("OrderDtoDeliveryAddress".equalsIgnoreCase(className)) {
      return new TypeToken<OrderDtoDeliveryAddress>(){}.getType();
    }
    
    if ("ReadOrder400Response".equalsIgnoreCase(className)) {
      return new TypeToken<ReadOrder400Response>(){}.getType();
    }
    
    if ("ServerErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<ServerErrorDto>(){}.getType();
    }
    
    if ("UnauthorizedErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<UnauthorizedErrorDto>(){}.getType();
    }
    
    if ("ValidationErrorDto".equalsIgnoreCase(className)) {
      return new TypeToken<ValidationErrorDto>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
